name: calendar_events_repository
description: A repository responsible for managing calendar events from Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: 3.1.15
  equatable: 2.0.3
  flutter:
    sdk: flutter
  meta: 1.8.0
  rxdart: 0.27.3
  simple_date: 1.0.0

dev_dependencies:
  coverage: 1.3.2
  mocktail: ^0.3.0
  test: 1.21.1
  very_good_analysis: ^3.0.0
