name: auth_repository
description: A repository responsible for managing authentication.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: 3.1.15
  equatable: 2.0.3
  firebase_auth: 3.3.18
  flutter:
    sdk: flutter
  google_sign_in: 5.3.1
  meta: 1.8.0
  rxdart: 0.27.3

dev_dependencies:
  coverage: 1.3.2
  mocktail: ^0.3.0
  test: 1.21.1
  very_good_analysis: ^3.0.0
