// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
// cspell:disable
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHnXsQJ2-K4Fyui_DDeqeX3udYjFCqmYU',
    appId: '1:39269630410:android:27ad16575b1d4efb834f33',
    messagingSenderId: '39269630410',
    projectId: 'buddy-86941',
    storageBucket: 'buddy-86941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgo6PaKUTpOZTU7xKZ1a7oL6upzpwLh_Q',
    appId: '1:39269630410:ios:5f30c490e8ae2da3834f33',
    messagingSenderId: '39269630410',
    projectId: 'buddy-86941',
    storageBucket: 'buddy-86941.appspot.com',
    androidClientId:
        '39269630410-179us3kaebhd9k5e4pvntgttcbresf6d.apps.googleusercontent.com',
    iosClientId:
        '39269630410-i6okef0bqeav6bed3grn2c9od181h3a5.apps.googleusercontent.com',
    iosBundleId: 'com.socialbuddybot.buddyBotCam',
  );
}
